name: Deploy Spring Boot to GCP

on:
  push:
    branches: ["master"]   # master에 push할 때 자동 배포됨

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew clean bootJar

      - name: Upload JAR to GCP server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/home/minhobot/coinserver/"
          strip_components: 2

      - name: Restart app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            pkill -f coinserver.jar || true
            cd /home/minhobot/coinserver
            LOGFILE=app_$(date +%y%m%d_%H%M%S).log
            setsid nohup java -jar coinserver.jar \
              --spring.config.location=/home/minhobot/coinserver/config/ \
              --server.address=0.0.0.0 \
              > "$LOGFILE" 2>&1 </dev/null &
              
